export const ZH_CHS: string;
export const EN: string;
export const JA: string;
export const AR: string;
export const ES: string;
export const DE: string;
export const RO: string;
export const RU: string;
export const FR: string;
export const PT_BR: string;
export const PL: string;
export const NL: string;
export const ZH_CHT: string;
export const TR: string;
export const languages: {
    [x: string]: {
        next: string;
        prev: string;
        first: string;
        last: string;
        pageInfo: string;
        notFound: string;
        clear: string;
        clearAll: string;
        maxSelected: string;
        placeholder: string;
        selectedCount: string;
        search: string;
    };
};
