export const [
  ZH_CHS, EN, JA, AR, ES, DE, RO, RU, FR, PT_BR, PL, NL, ZH_CHT
] = [
  'zh-chs', 'en', 'ja', 'ar', 'es', 'es', 'de', 'ro', 'ru', 'fr', 'pt-br', 'pl', 'nl', 'zh-cht'
]

export const languages = {
  [ZH_CHS]: { // Chinese
    next: '下一页',
    prev: '上一页',
    first: '首页',
    last: '尾页',
    close_btn: '关闭 (Esc键)',
    loading: '读取中...',
    pageInfo: '第 page_num/page_count 页( 共 row_count 条记录 )',
    notFound: '无查询结果',
    serverError: '连接到服务器时发生错误！',
    clear: '清除内容',
    selectAll: '选择当前页项目',
    unselectAll: '取消选择当前页项目',
    clearAll: '清除全部已选择项目',
    maxSelected: '最多只能选择 max_selected_limit 个项目',
    placeholder: '请选择一个项目',
    itemsSelected: '已选择 selected_count 个项目'
  },
  [EN]: { // English
    next: 'Next page',
    prev: 'Previous page',
    first: 'First page',
    last: 'Last page',
    close_btn: 'Close (Esc key)',
    loading: 'loading...',
    pageInfo: 'Page page_num/page_count ( row_count records )',
    notFound: 'not found',
    serverError: 'An error occurred while connecting to server.',
    clear: 'Clear content',
    selectAll: 'Select current page',
    unselectAll: 'Clear current page',
    clearAll: 'Clear all selected',
    maxSelected: 'You can only select up to max_selected_limit items',
    placeholder: 'Select an option',
    itemsSelected: 'selected_count items selected'
  },
  [JA]: { // Japanese
    next: '次へ',
    prev: '前へ',
    first: '最初のページへ',
    last: '最後のページへ',
    close_btn: '閉じる (Esc キー)',
    loading: '読み込み中...',
    pageInfo: 'page_num/page_count 件 ( 全 row_count つ記録 )',
    notFound: '(0 件)',
    serverError: 'サーバとの通信でエラーが発生しました。',
    clear: 'コンテンツをクリアする',
    selectAll: '当ページを選びます',
    unselectAll: '移して当ページを割ります',
    clearAll: '選択した項目をクリアする',
    maxSelected: '最多で max_selected_limit のプロジェクトを選ぶことしかできません',
    placeholder: 'プロジェクトを選択してください',
    itemsSelected: 'selected_count アイテムが選択されました'
  },
  [AR]: { // Arabic
    next: 'التالي',
    prev: 'السابق',
    first: 'الاول',
    last: 'الأخير',
    close_btn: 'إغلاق عند الضغط على زر (Esc)',
    loading: 'جاري التحميل ...',
    pageInfo: 'صفحة page_num/page_count ( row_count سجلات )',
    notFound: 'لا يوجد نتائج',
    serverError: 'لقد حدث خطأ أثناء الإتصال بالخادم.',
    clear: 'محو المحتوى',
    selectAll: 'تحديد الصفحة الحالية',
    unselectAll: 'إلغاء تحديد الصفحة الحالية',
    clearAll: 'إلغاء التحديد',
    maxSelected: 'يمكنك فقط تحديد (max_selected_limit) عناصر',
    placeholder: 'رجاء حدد الخيار',
    itemsSelected: 'تم تحديد (selected_count) عناصر'
  },
  [ES]: { // Spanish
    next: 'Siguiente página',
    prev: 'Pagina anterior',
    first: 'Primera página',
    last: 'última página',
    close_btn: 'Cerrar (tecla Esc)',
    loading: 'Cargando ...',
    pageInfo: 'Página page_num/page_count ( row_count registros )',
    notFound: 'no encontrado',
    serverError: 'Ocurrió un error al conectarse al servidor.',
    clear: 'Borrar contenido',
    selectAll: 'Seleccionar página actual',
    unselectAll: 'Borrar la página actual',
    clearAll: 'Borrar todo lo seleccionado',
    maxSelected: 'Solo puedes seleccionar hasta max_selected_limit items',
    placeholder: 'Seleccione una opción',
    itemsSelected: 'selected_count items Seleccionado'
  },
  [DE]: { // German
    next: 'Nächste Seite',
    prev: 'Vorherige Seite',
    first: 'Erste Seite',
    last: 'Letzte Seite',
    close_btn: 'Schließen (Esc)',
    loading: 'Lädt...',
    pageInfo: 'Seite page_num/page_count ( row_count Einträge )',
    notFound: 'Nicht gefunden',
    serverError: 'Bei der Verbindung zum Server ist ein Fehler aufgetreten.',
    clear: 'Inhalt löschen',
    selectAll: 'Aktuelle Seite auswählen',
    unselectAll: 'Auswahl der aktuellen Seite aufheben',
    clearAll: 'Alle ausgewählten löschen',
    maxSelected: 'Sie können nur bis zu max_selected_limit Elemente auswählen',
    placeholder: 'Wählen',
    itemsSelected: 'selected_count Elemente ausgewählt'
  },
  [RO]: { // Romanian
    next: 'Pagina următoare',
    prev: 'Pagina precedentă',
    first: 'Prima pagină',
    last: 'Ultima pagină',
    close_btn: 'Închide (tasta Esc)',
    loading: 'se încarcă...',
    pageInfo: 'Pagina page_num/page_count ( row_count înregistrări )',
    notFound: 'nu a fost găsit',
    serverError: 'O eroare a apărut în timpul conectării la server.',
    clear: 'Șterge conținutul',
    selectAll: 'Selectează pagina curentă',
    unselectAll: 'Deselectează pagina curentă',
    clearAll: 'Șterge înregistrările selectate',
    maxSelected: 'Poți selecta până la max_selected_limit înregistrări',
    placeholder: 'Selectează o înregistrare',
    itemsSelected: 'selected_count înregistrări selectate'
  },
  [RU]: { // Russian
    next: 'Вперед',
    prev: 'Назад',
    first: 'В начало',
    last: 'В конец',
    close_btn: 'Закрыть (Esc)',
    loading: 'загрузка...',
    pageInfo: 'Стр. page_num/page_count (всего - row_count)',
    notFound: 'Нет данных',
    serverError: 'Ошибка загрузки данных',
    clear: 'Очистить',
    selectAll: 'Выбрать все',
    unselectAll: 'Сбросить все',
    clearAll: 'Очистить выбранное',
    maxSelected: 'Нельзя выбрать более max_selected_limit значений',
    placeholder: 'Выберите значение',
    itemsSelected: 'selected_count - выбрано'
  },
  [FR]: { // French
    next: 'Page suivante',
    prev: 'Page précédente',
    first: 'Première page',
    last: 'Dernière page',
    close_btn: 'Fermer (touche Esc)',
    loading: 'chargement...',
    pageInfo: 'Page page_num/page_count ( row_count lignes )',
    notFound: 'Aucun résultat',
    serverError: 'Une erreur s\'est produite lors de la connexion avec le serveur.',
    clear: 'Effacer',
    selectAll: 'Sélectionner tous les éléments de la page',
    unselectAll: 'Déselectionner tous les élements de la page',
    clearAll: 'Tout déselectionner',
    maxSelected: 'Vous ne pouvez pas sélectionner plus de max_selected_limit élements',
    placeholder: 'Sélectionnez une option',
    itemsSelected: 'selected_count éléments sélectionnés'
  },
  [PT_BR]: { // Portuguese-Brazil
    next: 'Página seguinte',
    prev: 'Página anterior',
    first: 'Primera página',
    last: 'Última página',
    close_btn: 'Encerrar (tecla Esc)',
    loading: 'Carregando ...',
    pageInfo: 'Página page_num/page_count ( row_count registros )',
    notFound: 'não encontrado',
    serverError: 'Ocorreu um erro ao conectar com o servidor.',
    clear: 'Apagar conteúdo',
    selectAll: 'Selecionar página atual',
    unselectAll: 'Apagar página atual',
    clearAll: 'Apagar itens selecionados',
    maxSelected: 'Máximo permitido max_selected_limit itens',
    placeholder: 'Selecione uma opção',
    itemsSelected: 'selected_count itens selecionados'
  },
  [PL]: { // Polish
    next: 'Następna',
    prev: 'Poprzednia',
    first: 'Pierwsza',
    last: 'Ostatnia',
    close_btn: 'Zamknij (ESC)',
    loading: 'Ładowanie...',
    pageInfo: 'Strona page_num/page_count ( row_count rekordów )',
    notFound: 'Nic nie znaleziono',
    serverError: 'Wystąpił problem w połączeniu z serwerem.',
    clear: 'Wyczyść',
    selectAll: 'Zaznacz wszystko',
    unselectAll: 'Usuń zaznaczenie',
    clearAll: 'Usuń wszystkie zaznaczone',
    maxSelected: 'Możesz zaznaczyć maksymalnie max_selected_limit',
    placeholder: 'Wybierz z listy',
    itemsSelected: 'selected_count zaznaczonych'
  },
  [NL]: { // Dutch
    next: 'Volgende pagina',
    prev: 'Vorige pagina',
    first: 'Eerste pagina',
    last: 'Laatste pagina',
    close_btn: 'Sluiten (Esc toets)',
    loading: 'laden...',
    pageInfo: 'Pagina page_num/page_count ( row_count items )',
    notFound: 'Niet gevonden',
    serverError: 'Er is een fout opgetreden tijdens het verbinden met de server',
    clear: 'Wissen',
    selectAll: 'Selecteer huidige pagina',
    unselectAll: 'Wis huidige pagina',
    clearAll: 'Wis selectie',
    maxSelected: 'Je kunt maar max_selected_limit items selecteren',
    placeholder: 'Kies een optie',
    itemsSelected: 'selected_count Items geselecteerd'
  },
  [ZH_CHT]: { // Traditional Chinese
    next: '下一頁',
    prev: '上一頁',
    first: '首頁',
    last: '尾頁',
    close_btn: '關閉 (Esc鍵)',
    loading: '讀取中...',
    pageInfo: '第 page_num/page_count 頁( 共 row_count 條記錄 )',
    notFound: '無查詢結果',
    serverError: '連接到服務器時發生錯誤！',
    clear: '清除內容',
    selectAll: '選擇當前頁項目',
    unselectAll: '取消選擇當前頁項目',
    clearAll: '清除全部已選擇項目',
    maxSelected: '最多只能選擇 max_selected_limit 個項目',
    placeholder: '請選擇一個項目',
    itemsSelected: '已選擇 selected_count 個項目'
  }
}
