import {
  LANG_PAGE_NUMBER,
  LANG_PAGE_COUNT,
  LANG_ROW_COUNT,
  LANG_MAX_SELECTED_LIMIT,
  LANG_SELECTED_COUNT
} from './core/constants'

export const [
  ZH_CHS, EN, JA, AR, ES, DE, RO, RU, FR, PT_BR, PL, NL, ZH_CHT, TR
] = [
  'zh-chs', 'en', 'ja', 'ar', 'es', 'de', 'ro', 'ru', 'fr', 'pt-br', 'pl', 'nl', 'zh-cht', 'tr'
]

export const languages = {
  [ZH_CHS]: { // Chinese
    next: '下一页',
    prev: '上一页',
    first: '首页',
    last: '尾页',
    pageInfo: `第 ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} 页(共 ${LANG_ROW_COUNT} 条记录)`,
    notFound: '无查询结果',
    clear: '清除内容',
    clearAll: '清除全部已选择项目',
    maxSelected: `最多只能选择 ${LANG_MAX_SELECTED_LIMIT} 个项目`,
    placeholder: '请选择一个项目',
    selectedCount: `已选择 ${LANG_SELECTED_COUNT} 个项目`,
    search: '搜索'
  },
  [EN]: { // English
    next: 'Next page',
    prev: 'Previous page',
    first: 'First page',
    last: 'Last page',
    pageInfo: `Page ${LANG_PAGE_NUMBER} of ${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} records)`,
    notFound: 'Data not found',
    clear: 'Clear content',
    clearAll: 'Clear all selected',
    maxSelected: `You can only select up to ${LANG_MAX_SELECTED_LIMIT} items`,
    placeholder: 'Select an option',
    selectedCount: `${LANG_SELECTED_COUNT} items selected`,
    search: 'Search'
  },
  [JA]: { // Japanese
    next: '次へ',
    prev: '前へ',
    first: '最初のページへ',
    last: '最後のページへ',
    pageInfo: `${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} 件 (全 ${LANG_ROW_COUNT} つ記録)`,
    notFound: '(0 件)',
    clear: 'コンテンツをクリアする',
    clearAll: '選択した項目をクリアする',
    maxSelected: `最多で ${LANG_MAX_SELECTED_LIMIT} のプロジェクトを選ぶことしかできません`,
    placeholder: 'プロジェクトを選択してください',
    selectedCount: `${LANG_SELECTED_COUNT} アイテムが選択されました`,
    search: '検索'
  },
  [AR]: { // Arabic
    next: 'التالي',
    prev: 'السابق',
    first: 'الاول',
    last: 'الأخير',
    pageInfo: `صفحة ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} سجلات)`,
    notFound: 'لا يوجد نتائج',
    clear: 'محو المحتوى',
    clearAll: 'إلغاء التحديد',
    maxSelected: `يمكنك فقط تحديد (${LANG_MAX_SELECTED_LIMIT}) عناصر`,
    placeholder: 'رجاء حدد الخيار',
    selectedCount: `تم تحديد (${LANG_SELECTED_COUNT}) عناصر`,
    search: 'يبحث'
  },
  [ES]: { // Spanish
    next: 'Siguiente página',
    prev: 'Pagina anterior',
    first: 'Primera página',
    last: 'última página',
    pageInfo: `Página ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} registros)`,
    notFound: 'no encontrado',
    clear: 'Borrar contenido',
    clearAll: 'Borrar todo lo seleccionado',
    maxSelected: `Solo puedes seleccionar hasta ${LANG_MAX_SELECTED_LIMIT} items`,
    placeholder: 'Seleccione una opción',
    selectedCount: `${LANG_SELECTED_COUNT} items Seleccionado`,
    search: 'Buscar'
  },
  [DE]: { // German
    next: 'Nächste Seite',
    prev: 'Vorherige Seite',
    first: 'Erste Seite',
    last: 'Letzte Seite',
    pageInfo: `Seite ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} Einträge)`,
    notFound: 'Nicht gefunden',
    clear: 'Inhalt löschen',
    clearAll: 'Alle ausgewählten löschen',
    maxSelected: `Sie können nur bis zu ${LANG_MAX_SELECTED_LIMIT} Elemente auswählen`,
    placeholder: 'Wählen',
    selectedCount: `${LANG_SELECTED_COUNT} Elemente ausgewählt`,
    search: 'Suchen'
  },
  [RO]: { // Romanian
    next: 'Pagina următoare',
    prev: 'Pagina precedentă',
    first: 'Prima pagină',
    last: 'Ultima pagină',
    pageInfo: `Pagina ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} înregistrări)`,
    notFound: 'nu a fost găsit',
    clear: 'Șterge conținutul',
    clearAll: 'Șterge înregistrările selectate',
    maxSelected: `Poți selecta până la ${LANG_MAX_SELECTED_LIMIT} înregistrări`,
    placeholder: 'Selectează o înregistrare',
    selectedCount: `${LANG_SELECTED_COUNT} înregistrări selectate`,
    search: 'Căutare'
  },
  [RU]: { // Russian
    next: 'Вперед',
    prev: 'Назад',
    first: 'В начало',
    last: 'В конец',
    pageInfo: `Стр. ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (всего - ${LANG_ROW_COUNT})`,
    notFound: 'Нет данных',
    clear: 'Очистить',
    clearAll: 'Очистить выбранное',
    maxSelected: `Нельзя выбрать более ${LANG_MAX_SELECTED_LIMIT} значений`,
    placeholder: 'Выберите значение',
    selectedCount: `${LANG_SELECTED_COUNT} - выбрано`,
    search: 'Поиск'
  },
  [FR]: { // French
    next: 'Page suivante',
    prev: 'Page précédente',
    first: 'Première page',
    last: 'Dernière page',
    pageInfo: `Page ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} lignes)`,
    notFound: 'Aucun résultat',
    clear: 'Effacer',
    clearAll: 'Tout déselectionner',
    maxSelected: `Vous ne pouvez pas sélectionner plus de ${LANG_MAX_SELECTED_LIMIT} élements`,
    placeholder: 'Sélectionnez une option',
    selectedCount: `${LANG_SELECTED_COUNT} éléments sélectionnés`,
    search: 'Recherche'
  },
  [PT_BR]: { // Portuguese-Brazil
    next: 'Página seguinte',
    prev: 'Página anterior',
    first: 'Primera página',
    last: 'Última página',
    pageInfo: `Página ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} registros)`,
    notFound: 'não encontrado',
    clear: 'Apagar conteúdo',
    clearAll: 'Apagar itens selecionados',
    maxSelected: `Máximo permitido ${LANG_MAX_SELECTED_LIMIT} itens`,
    placeholder: 'Selecione uma opção',
    selectedCount: `${LANG_SELECTED_COUNT} itens selecionados`,
    search: 'Procurar'
  },
  [PL]: { // Polish
    next: 'Następna',
    prev: 'Poprzednia',
    first: 'Pierwsza',
    last: 'Ostatnia',
    pageInfo: `Strona ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} rekordów)`,
    notFound: 'Nic nie znaleziono',
    clear: 'Wyczyść',
    clearAll: 'Usuń wszystkie zaznaczone',
    maxSelected: `Możesz zaznaczyć maksymalnie ${LANG_MAX_SELECTED_LIMIT}`,
    placeholder: 'Wybierz z listy',
    selectedCount: `${LANG_SELECTED_COUNT} zaznaczonych`,
    search: 'Szukaj'
  },
  [NL]: { // Dutch
    next: 'Volgende pagina',
    prev: 'Vorige pagina',
    first: 'Eerste pagina',
    last: 'Laatste pagina',
    pageInfo: `Pagina ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} (${LANG_ROW_COUNT} items)`,
    notFound: 'Niet gevonden',
    clear: 'Wissen',
    clearAll: 'Wis selectie',
    maxSelected: `Je kunt maar ${LANG_MAX_SELECTED_LIMIT} items selecteren`,
    placeholder: 'Kies een optie',
    selectedCount: `${LANG_SELECTED_COUNT} Items geselecteerd`,
    search: 'Zoekopdracht'
  },
  [ZH_CHT]: { // Traditional Chinese
    next: '下一頁',
    prev: '上一頁',
    first: '首頁',
    last: '尾頁',
    pageInfo: `第 ${LANG_PAGE_NUMBER}/${LANG_PAGE_COUNT} 頁(共 ${LANG_ROW_COUNT} 條記錄)`,
    notFound: '無查詢結果',
    clear: '清除內容',
    clearAll: '清除全部已選擇項目',
    maxSelected: `最多只能選擇 ${LANG_MAX_SELECTED_LIMIT} 個項目`,
    placeholder: '請選擇一個項目',
    selectedCount: `已選擇 ${LANG_SELECTED_COUNT} 個項目`,
    search: '搜索'
  },
  [TR]: { // Turkish
    next: 'Sonraki',
    prev: 'Önceki',
    first: 'İlk',
    last: 'Son',
    pageInfo: 'Sayfa page_num/page_count ( row_count kayıt )',
    notFound: 'Bulunamadı',
    clear: 'İçeriği temizle',
    clearAll: 'Tüm seçilenleri bırak',
    maxSelected: 'Sadece max_selected_limit kadar seçim yapabilirsin.',
    placeholder: 'Seçim yapınız.',
    selectedCount: 'selected_count seçildi.',
    search: 'Aramak'
  }
}
